name: Django CI

on:
  push:
    branches:
      - master  # masterブランチにpushしたときにトリガー
  pull_request:
    branches:
      - master  # masterブランチへのプルリクエストがトリガー

jobs:
  test:
    runs-on: ubuntu-latest  # Ubuntu上でテストを実行

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # リポジトリのコードをチェックアウト

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # 必要なPythonのバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Djangoの依存関係をインストール

    - name: Run migrations
      run: python manage.py migrate  # Djangoのマイグレーションを実行

    - name: Run tests
      run: python manage.py test  # Djangoのテストを実行

